// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozpjdtvkdhbrftaupvyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96cGpkdHZrZGhicmZ0YXVwdnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTAzOTEsImV4cCI6MjA1NTcyNjM5MX0.loECAKgU_Tt0DmA0WuBItqcbXmN80YvGsliKQ_kSKYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);